spring.datasource.url=jdbc:mysql://localhost:3306/recruitment_system
spring.datasource.username=root
spring.datasource.password=2AV22CS014

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true